# Generated by Django 4.1.5 on 2023-01-17 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("block", models.CharField(max_length=100)),
                ("unit", models.IntegerField()),
                ("description", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("detailed_type", models.CharField(max_length=100)),
                ("special_type", models.CharField(max_length=100)),
                ("lrv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("urv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("units", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=50)),
                ("serial_no", models.CharField(blank=True, max_length=50)),
                ("system_type", models.CharField(blank=True, max_length=50)),
                ("equipment", models.CharField(blank=True, max_length=50)),
                ("project", models.CharField(blank=True, max_length=100)),
                ("interval", models.IntegerField()),
                ("last_checked", models.DateTimeField(default=datetime.datetime.now)),
                ("next_check", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.TextField()),
                (
                    "data_sheet",
                    models.FileField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="realtors.realtor",
                    ),
                ),
            ],
        ),
    ]
