# Generated by Django 4.1.5 on 2023-02-24 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("block", models.CharField(max_length=100)),
                ("unit", models.IntegerField()),
                ("description", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("detailed_type", models.CharField(max_length=100)),
                ("special_type", models.CharField(max_length=100)),
                ("lrv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("urv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("units", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=50)),
                ("serial_no", models.CharField(blank=True, max_length=50)),
                ("system_type", models.CharField(blank=True, max_length=50)),
                ("equipment", models.CharField(blank=True, max_length=50)),
                ("project", models.CharField(blank=True, max_length=100)),
                ("interval", models.IntegerField()),
                ("last_checked", models.DateTimeField(default=datetime.datetime.now)),
                ("next_check", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.TextField()),
                (
                    "data_sheet",
                    models.FileField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="realtors.realtor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("date_created", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="reports_files/%Y/%m/%d/",
                        verbose_name="Files",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reports",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FullReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("date_created", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to="reports_files/%Y/%m/%d/",
                        verbose_name="Files",
                    ),
                ),
                (
                    "output_0_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_25_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_50_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_75_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_100_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_0_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_25_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_50_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_75_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_100_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "manifold_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "ferrules_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "seal_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "mounting_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "cable_gland_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "insulation_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "general_state_correct",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fullreports",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
