# Generated by Django 4.1.5 on 2023-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="next_check",
            field=models.DateTimeField(blank=True),
        ),
    ]
