# Generated by Django 4.1.5 on 2023-03-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_fullreport_id_alter_listing_id_alter_report_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullreport",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fullreports",
                to="listings.listing",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="listings.listing",
            ),
        ),
    ]
