# Generated by Django 4.1.5 on 2023-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_next_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="next_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
