# Generated by Django 4.1.5 on 2023-01-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="listings.listing"
            ),
        ),
    ]
