# Generated by Django 4.1.5 on 2023-01-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_file_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="listings.listing",
            ),
        ),
    ]
