# Generated by Django 4.1.5 on 2023-01-27 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_file_date_created_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="file",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FileField(
                    blank=True, null=True, upload_to="reports_files/%Y/%m/%d/"
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
