# Generated by Django 4.1.5 on 2023-01-28 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_remove_listing_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(auto_created=True, max_length=50)),
                ("date_created", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="reports_files/%Y/%m/%d/",
                        verbose_name="Files",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reports",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
