# Generated by Django 4.1.5 on 2023-01-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
