# Generated by Django 4.1.5 on 2023-01-29 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_alter_report_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("date_created", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="reports_files/%Y/%m/%d/",
                        verbose_name="Files",
                    ),
                ),
                (
                    "output_0_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_25_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_50_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_75_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_100_before_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_0_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_25_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_50_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_75_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "output_100_after_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "manifold_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "ferrules_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "seal_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "mounting_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "cable_gland_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "insulation_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "general_state_correct",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("YES/TEMPORARY", "YES/TEMPORARY"),
                            ("NO", "NO"),
                            ("N/A", "N/A"),
                            ("NOT CHECKED", "NOT CHECKED"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fullreports",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
