# Generated by Django 4.1.5 on 2023-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_alter_fullreport_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullreport",
            name="file",
            field=models.FilePathField(
                path="C:\\Users\\ALEXIS\\OneDrive\\PYTHON-LESSONS\\DJANGO-ALL\\instruments_project\\media\\excel_files"
            ),
        ),
    ]
