# Generated by Django 4.1.5 on 2023-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0018_alter_fullreport_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullreport",
            name="cable_gland_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fullreport",
            name="ferrules_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fullreport",
            name="general_state_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fullreport",
            name="insulation_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fullreport",
            name="manifold_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fullreport",
            name="mounting_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fullreport",
            name="seal_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "YES"),
                    ("YES/TEMPORARY", "YES/TEMPORARY"),
                    ("NO", "NO"),
                    ("N/A", "N/A"),
                    ("NOT CHECKED", "NOT CHECKED"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
