# Generated by Django 4.1.5 on 2023-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0019_alter_fullreport_cable_gland_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullreport",
            name="file",
            field=models.FileField(
                blank=True, upload_to="reports_files/%Y/%m/%d/", verbose_name="Files"
            ),
        ),
    ]
