# Generated by Django 4.1.5 on 2023-02-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
